carpeta partials y partials footer en index, login y register
nbelelli/grupo_3_simple_gift pull request #29
Opened 2020-11-04 22:58 UTC by Brunsen1

2020-11-05 06:25 UTC, nbelelli requested changes
@Brunsen1 Segun lo veo, hiciste 2 partials:
- uno para el footer, donde esta incluido el head del html, esto no deberia estar aca, el partial del footer solo deberia tener html del footer
- otro partial que incluye ambos head y header, estas dos cosas son distintas, deberia cada cual tener su partial. 
Mi sugerencia es dejar que cada html tenga su head (o sea, que el head no este en ningun partial al menos por ahora) y que los partials de header y footer contentan solo las partes de html que corresponden a cada una de estas secciones.

2020-11-05 06:25 UTC, nbelelli commented on myapp/views/Partials/footer.ejs
> +<!DOCTYPE html>
¿Esto es un head de HTML adentro del partial de footer?
El Partial solo deberia contener el html del footer en este caso.

2020-11-05 06:25 UTC, nbelelli commented on myapp/views/Partials/head.ejs
> +<!DOCTYPE html>
El header no deberia ser parte del partial del head, son dos cosas distintas.

2020-11-06 02:45 UTC, adrianpuche12 approved these changes

2020-11-07 13:45 UTC, Brunsen1 reviewed
OK

2020-11-07 13:46 UTC, merged